### PR TITLE
Add golang test scripts

### PR DESCRIPTION
**Pull request by QuanZhang-William**
This commit adds the test scripts for golang catalog, adding vendor directory from [plumbing scripts](https://github.com/tektoncd/plumbing/tree/main/scripts).

### CODE REVIEW

**Comment by QuanZhang-William** [comment]
/cc @vdemeester @vinamra28. This PR is ready to review PTAL. 

I will update the trigger in the plumbing repo after this is completed for an end-to-end test

**Review by vdemeester — APPROVED** [review]

**Review by vinamra28 — APPROVED** [review]

**Pull request merged**
