### PR TITLE
Add test cases for golang catalog

### PR DESCRIPTION
**Pull request by QuanZhang-William**
This commit adds test cases for golang catalog. Golang catalog test script will be sent out separately after  https://github.com/tektoncd/plumbing/pull/1323 is merged.

A tested e2e example can be found in: https://github.com/QuanZhang-William/golang/tree/test-pipelines

### CODE REVIEW

**Comment by QuanZhang-William** [comment]
cc @vdemeester @vinamra28

**Comment by QuanZhang-William** [comment]
Part of https://github.com/tektoncd-catalog/golang/issues/3

**Comment by QuanZhang-William** [comment]
@vdemeester @vinamra28 

I'm not sure whether we need some extra setup in the cluster if we want to use custom [GOARCH](https://github.com/tektoncd-catalog/golang/blob/main/task/golang-build/golang-build.yaml#L35) param (like s390x or ppc64le)? This seems like a potential use case of matrix as documented [here](https://github.com/tektoncd/community/blob/main/teps/0118-matrix-with-explicit-combinations-of-parameters.md#adding-a-specific-combination-in-the-matrix)

**Review by vdemeester — APPROVED** [review]
> I'm not sure whether we need some extra setup in the cluster if we want to use custom [GOARCH](https://github.com/tektoncd-catalog/golang/blob/main/task/golang-build/golang-build.yaml#L35) param (like s390x or ppc64le)? This seems like a potential use case of matrix as documented [here](https://github.com/tektoncd/community/blob/main/teps/0118-matrix-with-explicit-combinations-of-parameters.md#adding-a-specific-combination-in-the-matrix)

We can use `GOARCH` in any cluster, no need for extra setup, it's all handled by the go compiler.

**Comment by QuanZhang-William** [comment]
> > I'm not sure whether we need some extra setup in the cluster if we want to use custom [GOARCH](https://github.com/tektoncd-catalog/golang/blob/main/task/golang-build/golang-build.yaml#L35) param (like s390x or ppc64le)? This seems like a potential use case of matrix as documented [here](https://github.com/tektoncd/community/blob/main/teps/0118-matrix-with-explicit-combinations-of-parameters.md#adding-a-specific-combination-in-the-matrix)
> 
> We can use `GOARCH` in any cluster, no need for extra setup, it's all handled by the go compiler.

Sounds good, I will try to dogfood matrix in this case.
/cc @jerop

**Pull request merged**
